FROM httpd:2.4

# Copia configuración personalizada
# COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf

# Copia tu sitio web al directorio público de Apache
# COPY ./workspace/apache/public-html/index.html /usr/local/apache2/htdocs/

# En el futuro podría ser implementado.
# Activamos soporte para archivos PHP si más adelante se conecta con otro contenedor que contenga PHP-FPM
# y se desea usar FastCGI en vez de mod_php. 

# Por defecto, el volumen /usr/local/apache2/htdocs será el sitio servido
