FROM python:alpine

# Creamos el directorio de trabajo
WORKDIR /workspace

# Instala dependencias si fuese necesario utilizando requirements.txt
# COPY requirements.txt .
# RUN pip install -r requirements.txt

# Comando por defecto: mantiene el contenedor corriendo
CMD ["tail", "-f", "/dev/null"]
