FROM node:23-alpine

# En el caso de querer instalar nuevas dependencias y ampliarlo, dejo un archivo de ejemplo llamado package.json:
# COPY package*.json ./
# RUN npm install

# Creamos el directorio de trabajo
WORKDIR /workspace

CMD ["tail", "-f", "/dev/null"]

# Si queremos que ejecute un archivo en específico de manera automática:
# CMD ["node", "index.js"]

